spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: arpita
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: arpita123

  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
    
server:
  port: 8081